db.kcoco_page_resource_download.insertMany([
{
	id: 1,
	key: 'share',
	title: '深度解读行业标杆案例——走进天马科技',
    desc: '全国餐饮收入27860亿元，同比增长9.7%，较上年加快了0.7个百分点，终止了2011年以来连续三年增速下滑的颓势',
    date: '2022-01-15',
    download: 22,
    downloadType: 'link',
    size: '1.2MB',
    href: 'pdf/1.pdf',
    type: 'txt',
    tag: ['客户案例'],
    search: ['爆炸','餐饮','食物','天马', '天马科技'],
	status: 1,
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 2,
	key: 'whitePage',
	title: '《餐饮企业解构层级规划白皮书》—— 揭秘解读',
	search: ['白皮书','餐饮','食物','pdf', '流量', '巨头', '趋势'],
	desc: '',
    date: '2022-02-08',
    href: 'pdf/1.pdf',
    download: 112,
	downloadType: 'normal',
	size: '21MB',
	type: 'pdf',
	tag: ['白皮书'],
	status: 1,
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 3,
	key: 'report',
    title: '行业报告——数字化转型探索之路',
    search: ['月光','企业','客户','行业指南', '流量', '分享', '趋势'],
    desc: '',
    date: '2022-02-17',
    download: 221,
    href: 'pdf/1.pdf',
    downloadType: 'normal',
    size: '16MB',
    type: 'pdf',
    tag: [],
	status: 1,
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 4,
    key: 'share',
    title: '《数机大会》餐饮行业时代，如何把控质量大关',
    search: ['盛会','吸引','留资','把控', '流量', '知识分享', '趋势'],
    desc: '经营者提出了理性要求，市场格局发生的变化，使竞争更激烈，经营者们也须不断调整思路，突出特色，以迎合顾客的需求，使其产品和服务更加适应市场的需要。在这种情况下，管理者能够把握这种变化的趋势，以适宜的产品、合理的价位、舒适的环境、优质的服务赢得了广大消费者的青睐，取得了市场上的成功',
    date: '2022-03-18',
    download: 12,
    downloadType: 'normal',
    size: '12.2MB',
    type: 'pdf',
    href: 'pdf/1.pdf',
    tag: ['大会解读'],
	status: 1,
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 5,
	key: 'product',
	title: '清水系统5.0版本正式发布',
	search: [],
    desc: '记得双击第四季度四等奖四等奖死就爱是妒忌爱是妒忌随机打劫啊打家劫舍大九十多斤啊多久啊',
    date: '2022-04-04',
    download: 88,
    href: 'pdf/1.pdf',
    downloadType: 'normal',
    size: '334.2MB',
    type: 'mp4',
    tag: ['产品解读', '产品更新'],
	status: 1,
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
])