db.kcoco_admin_url_permission.insertMany([
{
	key: '/api/user/create/auth',
	name: '创建系统用户',
	status: 1,
	remark: '',
	roles: ['superAdmin'],
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	key: '/api/user/delete/auth',
	name: '删除系统用户',
	status: 1,
	remark: '',
	roles: ['superAdmin'],
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	key: '/api/user/resetPassword/auth',
	name: '重置用户密码',
	status: 1,
	remark: '',
	roles: ['superAdmin'],
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	key: '/api/user/update/auth',
	name: '修改用户信息',
	status: 1,
	remark: '',
	roles: ['superAdmin','admin'],
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	key: '/api/user/list/auth',
	name: '获取用户列表',
	status: 1,
	remark: '',
	roles: ['superAdmin','admin'],
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	key: '/api/user/test/auth',
	name: '获取用户列表',
	status: 1,
	remark: '',
	roles: ['superAdmin','admin'],
	createTime: new Date(),
	modifyTime: new Date(),
}
])