db.kcoco_admin_menu.insertMany([
  {
    title: '个人信息',
    key: 'person',
    path: '/admin/person',
    roles: [],
    level: 1,
    hasLink: 1,
    hasIcon: 1,
    iconKey: 'userOutlined',
    hasChild: 0,
    order: 1,
    isCommon: 1,
    status: 1
  },
  {
    title: '首页',
    key: 'index',
    path: '/admin/index',
    roles: [],
    level: 1,
    hasLink: 1,
    hasIcon: 1,
    iconKey: 'homeOutlined',
    hasChild: 0,
    order: 9999,
    isCommon: 1,
    status: 1
  },
    {
    title: '官网配置',
    key: 'web',
    path: '/admin/web',
    hasLink: 0,
    hasIcon: 1,
    iconKey: 'desktopOutlined',
    level: 1,
    hasChild: 1,
    roles: ['hr', 'web'],
    order: 100,
    status: 1
  },
  {
    title: '首页配置',
    key: 'web_index',
    path: '/admin/web/index',
    hasIcon: 1,
    iconKey: 'appstoreOutlined',
    hasChild: 1,
    hasLink: 0,
    level: 2,
    parentMenu: 'web',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: 'banner配置',
    key: 'web_index_banner',
    path: '/admin/web/index/banner',
    iconKey: '',
    hasChild: 0,
    hasLink: 1,
    hasIcon: 0,
    level: 3,
    parentMenu: 'web_index',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '新闻配置',
    key: 'web_index_news',
    path: '/admin/web/index/news',
    iconKey: '',
    hasChild: 0,
    hasLink: 1,
    hasIcon: 0,
    level: 3,
    parentMenu: 'web_index',
    roles: ['web'],
    order: 100,
    status: 1
  },
    {
    title: '栏目配置',
    key: 'web_index_column',
    path: '/admin/web/index/column',
    iconKey: '',
    hasChild: 0,
    hasLink: 1,
    hasIcon: 0,
    level: 3,
    parentMenu: 'web_index',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '招聘管理',
    key: 'web_resume',
    path: '/admin/web/resume',
    hasIcon: 1,
    iconKey: 'userSwitchOutlined',
    hasChild: 1,
    hasLink: 0,
    level: 2,
    parentMenu: 'web',
    roles: ['web', 'hr'],
    order: 100,
    status: 1
  },
   {
    title: '岗位管理',
    key: 'web_resume_list',
    path: '/admin/web/resume/list',
    hasIcon: 0,
    hasChild: 0,
    hasLink: 1,
    level: 3,
    parentMenu: 'web_resume',
    roles: ['web', 'hr'],
    order: 100,
    status: 1
  },
  {
    title: '类型管理',
    key: 'web_resume_type',
    path: '/admin/web/resume/type',
    hasIcon: 0,
    hasChild: 0,
    hasLink: 1,
    level: 3,
    parentMenu: 'web_resume',
    roles: ['web', 'hr'],
    order: 100,
    status: 1
  },
   {
    title: '标签管理',
    key: 'web_resume_tag',
    path: '/admin/web/resume/tag',
    hasIcon: 0,
    hasChild: 0,
    hasLink: 1,
    level: 3,
    parentMenu: 'web_resume',
    roles: ['web', 'hr'],
    order: 100,
    status: 1
  },
    {
    title: '案例管理',
    key: 'web_case',
    path: '/admin/web/case',
    hasIcon: 1,
    iconKey: 'contactsOutlined',
    hasChild: 1,
    hasLink: 0,
    level: 2,
    parentMenu: 'web',
    roles: ['web'],
    order: 100,
    status: 1
  },
   {
    title: '案例列表',
    key: 'web_case_list',
    path: '/admin/web/case/list',
    hasIcon: 0,
    hasChild: 0,
    hasLink: 1,
    level: 3,
    parentMenu: 'web_case',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '热门标签',
    key: 'web_case_tag',
    path: '/admin/web/case/tag',
    hasIcon: 0,
    hasChild: 0,
    hasLink: 1,
    level: 3,
    parentMenu: 'web_case',
    roles: ['web'],
    order: 100,
    status: 1
  },
 {
    title: '活动管理',
    key: 'web_activity',
    path: '/admin/web/activity',
    hasIcon: 1,
    iconKey: 'accountBookOutlined',
    hasChild: 1,
    hasLink: 0,
    level: 2,
    parentMenu: 'web',
    roles: ['web'],
    order: 100,
    status: 1
  },
   {
    title: '产品活动',
    key: 'web_activity_product',
    path: '/admin/web/activity/product',
    hasIcon: 0,
    hasChild: 0,
    hasLink: 1,
    level: 3,
    parentMenu: 'web_activity',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '热门活动',
    key: 'web_activity_hot',
    path: '/admin/web/activity/hot',
    hasIcon: 0,
    hasChild: 0,
    hasLink: 1,
    level: 3,
    parentMenu: 'web_activity',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '品牌活动',
    key: 'web_activity_brand',
    path: '/admin/web/activity/brand',
    hasIcon: 0,
    hasChild: 0,
    hasLink: 1,
    level: 3,
    parentMenu: 'web_activity',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '资源管理',
    key: 'web_resource',
    path: '/admin/web/resource',
    hasIcon: 1,
    iconKey: 'fileDoneOutlined',
    hasChild: 1,
    hasLink: 0,
    level: 2,
    parentMenu: 'web',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '资源列表',
    key: 'web_resource_list',
    path: '/admin/web/resource/list',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'web_resource',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '栏目管理',
    key: 'web_resource_column',
    path: '/admin/web/resource/column',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'web_resource',
    roles: ['web'],
    order: 100,
    status: 1
  },
    {
    title: '分类管理',
    key: 'web_resource_category',
    path: '/admin/web/resource/category',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'web_resource',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '新闻管理',
    key: 'web_news',
    path: '/admin/web/news',
    hasIcon: 1,
    iconKey: 'profileOutlined',
    hasChild: 1,
    hasLink: 0,
    level: 2,
    parentMenu: 'web',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '新闻列表',
    key: 'web_news_list',
    path: '/admin/web/news/list',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'web_news',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '分类管理',
    key: 'web_news_category',
    path: '/admin/web/news/category',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'web_news',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: 'tdk管理',
    key: 'web_tdk',
    path: '/admin/web/tdk',
    hasIcon: 1,
    iconKey: 'reconciliationOutlined',
    hasChild: 0,
    hasLink: 1,
    level: 2,
    parentMenu: 'web',
    roles: ['web'],
    order: 100,
    status: 1
  },
  {
    title: '数据管理',
    key: 'data',
    path: '/admin/data',
    iconKey: 'databaseOutlined',
    level: 1,
    hasIcon: 1,
    hasLink: 0,
    hasChild: 1,
    roles: ['admin','superAdmin','data'],
    order: 100,
    status: 1
  },
  {
    title: '官网数据',
    key: 'data_web',
    path: '/admin/data/web',
    hasIcon: 1,
    iconKey: 'consoleSqlOutlined',
    hasChild: 1,
    hasLink: 0,
    level: 2,
    parentMenu: 'data',
    roles: ['admin', 'superAdmin','data'],
    order: 100,
    status: 1
  },
    {
    title: '线索管理',
    key: 'data_web_clue',
    path: '/admin/data/web/clue',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'data_web',
    roles: ['admin', 'superAdmin','data'],
    order: 100,
    status: 1
  },
    {
    title: '资源数据',
    key: 'data_web_resource',
    path: '/admin/data/web/resource',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'data_web',
    roles: ['admin', 'superAdmin','data'],
    order: 100,
    status: 1
  },
  {
    title: '新闻数据',
    key: 'data_web_news',
    path: '/admin/data/web/news',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'data_web',
    roles: ['admin', 'superAdmin','data'],
    order: 100,
    status: 1
  },
    {
    title: '案例数据',
    key: 'data_web_case',
    path: '/admin/data/web/case',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'data_web',
    roles: ['admin', 'superAdmin','data'],
    order: 100,
    status: 1
  },
    {
    title: '活动数据',
    key: 'data_web_activity',
    path: '/admin/data/web/activity',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'data_web',
    roles: ['admin', 'superAdmin','data'],
    order: 100,
    status: 1
  },
   {
    title: 'PV/UV',
    key: 'data_web_pvuv',
    path: '/admin/data/web/pvuv',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'data_web',
    roles: ['admin', 'superAdmin', 'data'],
    order: 100,
    status: 1
  },
   {
    title: 'TP',
    key: 'data_web_tp',
    path: '/admin/data/web/tp',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'data_web',
    roles: ['admin', 'superAdmin','data'],
    order: 100,
    status: 1
  },
  {
    title: '应用管理',
    key: 'app',
    path: '/admin/app',
    iconKey: 'macCommandOutlined',
    level: 1,
    hasIcon: 1,
    hasLink: 0,
    hasChild: 1,
    roles: ['admin','superAdmin','web'],
    order: 80,
    status: 1
  },
  {
    title: '菜单管理',
    key: 'app_menu',
    path: '/admin/app/menu',
    level: 2,
    hasIcon: 1,
    iconKey: 'menuOutlined',
    hasLink: 1,
    hasChild: 0,
    parentMenu: 'app',
    roles: ['admin','superAdmin'],
    order: 72,
    status: 1
  },
    {
    title: '路由管理',
    key: 'app_route',
    path: '/admin/app/route',
    level: 2,
    hasIcon: 1,
    iconKey: 'linkOutlined',
    hasLink: 1,
    hasChild: 0,
    parentMenu: 'app',
    roles: ['admin','superAdmin'],
    order: 72,
    status: 1
  },
  {
    title: '缓存管理',
    key: 'app_cache',
    path: '/admin/app/cache',
    level: 2,
    hasIcon: 1,
    iconKey: 'hourglassOutlined',
    hasLink: 1,
    hasChild: 0,
    parentMenu: 'app',
    roles: ['admin','superAdmin', 'web'],
    order: 71,
    status: 1
  },
  {
    title: '权限管理',
    key: 'app_permission',
    path: '/admin/app/permission',
    level: 2,
    hasIcon: 1,
    iconKey: 'frownOutlined',
    hasLink: 0,
    hasChild: 1,
    parentMenu: 'app',
    roles: ['admin','superAdmin'],
    order: 71,
    status: 1
},
{
    title: 'UI权限',
    key: 'app_permission_ui',
    path: '/admin/app/permission/ui',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'app_permission',
    roles: ['admin', 'superAdmin'],
    order: 71,
    status: 1
  },
  {
    title: 'url权限',
    key: 'app_permission_url',
    path: '/admin/app/permission/url',
    hasChild: 0,
    hasLink: 1,
    level: 3,
    hasIcon: 0,
    parentMenu: 'app_permission',
    roles: ['admin', 'superAdmin'],
    order: 71,
    status: 1
  },
  {
    title: '角色管理',
    key: 'app_role',
    path: '/admin/app/role',
    level: 2,
    hasIcon: 1,
    iconKey: 'trademarkOutlined',
    hasLink: 1,
    hasChild: 0,
    parentMenu: 'app',
    roles: ['admin','superAdmin'],
    order: 71,
    status: 1
  },
  {
    title: '用户管理',
    key: 'userManage',
    path: '/admin/userManage',
    iconKey: 'teamOutlined',
    level: 1,
    hasIcon: 1,
    hasLink: 1,
    hasChild: 0,
    roles: ['admin','superAdmin'],
    order: 2,
    status: 1
  }
])