db.kcoco_page_common_tag.insertMany([
{
	mainKey: 'news_tag',
	secKey: 'brand',
	name: '品牌输出',
	remark: '新闻标签',
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	mainKey: 'news_tag',
	secKey: 'fruit',
	name: '水果联盟',
	remark: '新闻标签',
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	mainKey: 'news_tag',
	secKey: 'report',
	name: '行业报告',
	remark: '新闻标签',
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	mainKey: 'news_tag',
	secKey: 'ai',
	name: '智能系统',
	remark: '新闻标签',
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	mainKey: 'news_tag',
	secKey: 'service',
	name: '服务合作',
	remark: '新闻标签',
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	mainKey: 'news_tag',
	secKey: 'solution',
	name: '解决方案',
	remark: '新闻标签',
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	mainKey: 'news_tag',
	secKey: 'sjdh',
	name: '数机大会',
	remark: '新闻标签',
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	mainKey: 'news_tag',
	secKey: 'product',
	name: '产品服务',
	remark: '新闻标签',
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	mainKey: 'news_tag',
	secKey: 'digital',
	name: '数字化',
	remark: '新闻标签',
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	mainKey: 'news_tag',
	secKey: 'report',
	name: '行业报告',
	remark: '新闻标签',
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
])