db.kcoco_page_case.insertMany([
{
	id: 1,
	title: '强化图腾20',
	desc: '法拉第的理论“提供数学方法基础”的愿望，决心把法拉第的天才思想以清晰准确的数学形式表示',
	key: ['案例','强化图腾','20'],
	icon: '/images/product/fruits/litchi/case/c6.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 2,
	title: '虚无宝石19',
	desc: '赫兹经过反复实验，发明了一种电波环，用这种电波环作了一系列的实验赫姆霍茨的学生',
	key: ['案例','虚无宝石','19'],
	icon: '/images/product/fruits/litchi/case/c5.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 3,
	title: '复仇者联盟18',
	desc: '因此在德国等欧洲中心地带毫无立足之地，甚而被当成奇谈怪论。当时支持电磁理论研',
	key: ['案例','复仇者联盟','18'],
	icon: '/images/product/fruits/litchi/case/c4.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 4,
	title: '冲击之刃17',
	desc: '完成了四年的学业，相形之下，爱丁堡大学这个摇篮已经不能满足麦克斯韦的求知欲。为了进一步深造',
	key: ['案例','冲击之刃','17'],
	icon: '/images/product/fruits/litchi/case/c3.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 5,
	title: '萝莉探店16',
	desc: '并把自己对科学史的爱好传给麦克斯韦。哈密顿教授则用广博的学识影响着他',
	key: ['案例','萝莉探店','16'],
	icon: '/images/product/fruits/litchi/case/c2.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 6,
	title: '居仁网络15',
	desc: '他培养了麦克斯韦对实验技术的浓厚兴趣，一个从事理论物理的人很难有这种兴趣',
	key: ['案例','居仁网络','15'],
	icon: '/images/product/fruits/litchi/case/c1.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 7,
	title: '猜你喜欢',
	desc: '对敌方目标释放这股能量可以对其造成伤害，使其被缠绕，并且净化其附近区域的魔法效果作',
	key: ['案例','虚妄诺言','14'],
	icon: '/images/product/fruits/orange/case/c5.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 8,
	title: '不朽之守护13',
	desc: '神谕者让目标沉醉，使其无法攻击，同时提高其100%的魔法抗性。可对友方和敌方单位施放',
	key: ['案例','不朽之守护','13'],
	icon: '/images/product/fruits/grape/case/c6.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 9,
	title: '龙骑士12',
	desc: '希望之家是全国打强大的元素领主奥拉基尔与拉格纳罗斯以及奥丹姆的尼斐塞特托维尔权的工作',
	key: ['案例','龙骑士','12'],
	icon: '/images/product/fruits/grape/case/c5.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 10,
	title: '首尔古德曼11',
	desc: '首尔古德曼全最终他败于其他守护巨龙之手，并退至深岩之洲的元素位面休养生息。他在那里观',
	key: ['案例','首尔古德曼','11'],
	icon: '/images/product/fruits/grape/case/c4.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 11,
	title: '本地兔子窝10',
	desc: '希望之家是全国打最大德间书店俩是的呢收到，通过全量审计公共功能，帮助希望之家鉴权的工作',
	key: ['案例','本地兔子窝','10'],
	icon: '/images/product/fruits/grape/case/c3.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 12,
	title: '好粥道道9',
	desc: '希望之家是全国打最大德间书店俩凡世与巨龙之中，他的名字已经成为了恐惧与蔑视的代名词',
	key: ['案例','好粥道道','9'],
	icon: '/images/product/fruits/grape/case/c2.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 13,
	title: '鱼米之乡8',
	desc: '希将目标身上一切不洁之物净化，对其造成大量魔法伤害，并使其在接下来的一段时间内逐渐鉴权的工作',
	key: ['案例','鱼米之乡','8'],
	icon: '/images/product/fruits/grape/case/c1.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 14,
	title: '五线科技7',
	desc: '他还成功让自己最大的敌人阿莱克丝塔萨成为了部落的奴隶，自己随后与部落结盟。在遭遇一系列挫折之后',
	key: ['案例','五线科技','7'],
	icon: '/images/product/fruits/apple/case/c1.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 15,
	title: '死亡之翼6',
	desc: '奈萨里奥是黑龙之王，曾为守护巨龙之一，大地的守护曾在外域幻化成人类',
	key: ['案例','死亡之翼','6'],
	icon: '/images/product/fruits/apple/case/c6.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 16,
	title: 'Home lander5',
	desc: 'Home lander是全国打最大德间书店俩是的呢收到，通过全量审计公共功能，帮助希望之家打造全作',
	key: ['案例','home','lander','5'],
	icon: '/images/product/fruits/apple/case/c5.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 17,
	title: '永恒族4',
	desc: '称为“天神”的宇宙生物创造出拥有超能力的永恒族和异常族，两个族群一直互相争斗的故事',
	key: ['案例','永恒族','4'],
	icon: '/images/product/fruits/apple/case/c4.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 18,
	title: '光照会3',
	desc: 'X战警这类超级英雄团体截然不同，是为了解决威胁地球乃至宇宙的危机而存在，主张以小的牺牲避免牲',
	key: ['案例','光照会','3'],
	icon: '/images/product/fruits/apple/case/c3.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 19,
	title: '地狱火俱乐部2',
	desc: '同素异形体之间的性质差异主要表现在物理性质上，化学性质上也有着活性的差异',
	key: ['案例','地狱火俱乐部','2'],
	icon: '/images/product/fruits/apple/case/c2.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	id: 20,
	title: '菲克尼尼1',
	desc: '菲克尼尼是全国打最大德间书店俩是的呢收到，通过全量审计公共功能，帮助希望之家打造全领域鉴权的工作',
	key: ['案例','菲克尼尼','1'],
	icon: '/images/product/dataserver/cluster/case/c1.svg',
	href: '/case/detail',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
])