db.kcoco_page_brand_activity.insertMany([
{
	title: '企业问道——客户才是第一生产力',
	desc: '分裂割据的后期，拉萨地区多次发生鲁悔、巴、惹、征四集团间的战争。1160年，在拉萨、雅隆澎波一带，四集团互相攻杀。连续不断的战争，不但给拉萨地区藏民的生命财产和农牧业生产带来很大危害',
	href: '/activity/detail',
	btnText: '查看详情',
	cover: '/images/activity/brand/b10.jpg',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '全球直播——科技创新之后的道路',
	desc: '迁都前的拉萨是一片沼泽荒芜；松赞干布迁都以后，造宫堡，修河道，建寺院，奠定了拉萨城市雏形。大昭寺就是这一时期建造的',
	href: '/about/news/15',
	btnText: '查看详情',
	cover: '/images/activity/brand/b9.jpg',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: 'yy科技10周年，邀你一起线上参加',
	desc: '品牌营销活动是现代商业活动的一种，将策划科学应用在品牌营销活动当中，就是所谓的品牌营销策划。策划在现代商业活动中的运用相当普及',
	href: '/activity/detail',
	btnText: '查看详情',
	cover: '/images/activity/brand/b8.jpg',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '出路？谁才是餐饮行业大赢家？',
	desc: '为了巩固和发展新建立起来的政权，避开以前地方上的各种的贵族豪酋势力的干扰，他决定将根据地从山南移到拉萨',
	href: '/activity/detail',
	btnText: '查看详情',
	cover: '/images/activity/brand/b7.jpg',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '企业问道——快、准、狠治理企业数据问题',
	desc: '品牌营销活动是现代商业活动的一种，将策划科学应用在品牌营销活动当中，就是所谓的品牌营销策划。策划在现代商业活动中的运用相当普及',
	href: '/about/news/11',
	btnText: '查看详情',
	cover: '/images/activity/brand/b6.jpg',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '走进客户——地狱火俱乐部的崛起',
	desc: '逍遥派不仅追求武学修为，同时对琴棋书画医无所不精，加入门派前许多人就已经是扬名于江湖的人物。门派中人不乏朝廷为官者也有游荡市井者，逍遥实际上是“一人之派”，逍遥者自逍遥所在',
	href: '/about/news/15',
	btnText: '查看详情',
	cover: '/images/activity/brand/b5.jpg',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '企业问道——如何制订有效的kpi？',
	desc: '天下武功唯快不破，天山武学讲究的也是个快字。天山武功以诡异著称，常人看来天山弟子几乎是一个鬼魂。天山弟子的攻击是外家功夫，总能在关键时刻连连暴击',
	href: '/about/news/10',
	btnText: '查看详情',
	cover: '/images/activity/brand/b4.jpg',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '2020神机大会，在北京顺利召开',
	desc: '品牌营销活动是现代商业活动的一种，将策划科学应用在品牌营销活动当中，就是所谓的品牌营销策划。策划在现代商业活动中的运用相当普及',
	href: '/about/news/9',
	btnText: '查看详情',
	cover: '/images/activity/brand/b3.jpg',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: 'Sass领域的蜕变之路',
	desc: '快速变化数据采集、传输、存储、处理（包括计算、分析、可视化等）、交换、销毁等覆盖数据生命周期相关活动的各种数据服务',
	href: '/about/news/3',
	btnText: '查看详情',
	cover: '/images/activity/brand/b2.jpg',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '城市大数据服务，带你走向胜利，无情宣发，剑指出路',
	desc: '科技部、国家发展改革委发布支持新一批城市开展创新型城市建设的名单，全国17座城市入选，拉萨名列其中',
	href: '/activity/detail',
	btnText: '查看详情',
	cover: '/images/activity/brand/b1.jpg',
	order: 1,
	status: 1,
	createTime: new Date(),
	modifyTime: new Date(),
}
])