db.kcoco_page_resume.insertMany([
{
  id: 1,
  key: 'practice',	
	title: '运营实习生',
	desc: '',
	category: 'operating',
  place: 'beijing',
	department: '市场部',
	date: '2022年04月18日',
  experience: '不限',
  education: '不限',
  isTop: 0,
  href: 'https://www.zhipin.com',
  contact: 'xxx@hr.com',
  duty: [
      '协助主管负责搭建、运营用户池群，裂变吸引精准新用户加入，促成用户转化',
      '协助主管负责社群内容发布、话题引导、用户答疑，提升核心用户留存率、复购率、转介绍率，挖掘、维护核心用户价值',
      '结合市场热点、产品营销节奏、即时热门话题、节假日等，挖掘用户需求，负责核心用户微信群的运营和管理，对核心用户的问题进行答疑和反馈，定期输出核心用户的想法与建议',
      '协助主管定期组织策划社群活动（线上+线下），推送信息至新老用户，关注社群内成员交流内容'
  ],
  require: [
      '抗压能力强，具备同理心',
      '学习能力，执行能力',
      '自我学习能力强，性格乐观开朗，有强烈的责任心和进取心'
  ],
	status: 1,
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
  id: 2,
	key: 'practice', 
	title: 'Java实习生',
	desc: '负责事业部产品（Saas）核心功能研发',
	category: 'technology',
  place: 'hangzhou',
	department: '研发中心',
	date: '2022年01月01日',
  experience: '不限',
  education: '本科及以上',
  href: 'https://www.zhipin.com',
  contact: 'xxx@hr.com',
  duty: ['负责事业部产品（Saas）核心功能研发'],
  require: [
	    '熟悉常用框架，如SpringBoot、SpringMVC、MyBatis，有实际项目开发经验',
	    '熟悉分布式、缓存、消息等机制，有高并发应用开发经验者优先',
	    '掌握Linux操作系统和常用数据库，对SQL优化有丰富的经验者优先',
	    '逻辑思维能力突出，有较强的学习能力和沟通能力',
	    '具备良好的执行力和责任心，能承受较大工作压力，能推动团队朝目标前进'
  ],
	status: 1,
  isTop: 0,
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
  id: 3,
	key: 'society', 
	title: '销售顾问',
	desc: '',
	category: 'sells',
  place: 'shanghai',
	department: '营销中心',
	date: '2022年02月01日',
  experience: '5年以上',
  education: '不限',
  href: 'https://www.zhipin.com',
  contact: 'xxx@hr.com',
  duty: [
      'B2B部门业务开发，涉及到B端小B，小ka，夫妻水果店，餐饮，美食，茶饮，水果榨汁店，以及所有B端只要可能用到水果的客户，进行客户开发、维护',
      '把握行业快速发展趋势，协调公司供应链优势，完成客户生意的深化发展',
      '根据商户需求并结合消费者消费动向，制定个性化营销方案，与商户谈判并达成合作',
      '执行公司的销售策略和政策，达成业绩目标',
      '与公司各部门有效配合，并快速有效的解决产品上线前后所遇到的问题及突发事件，及时处理来自商家及消费者的投诉、反馈、建议等'
  ],
  require: [
      '一年以上销售经验，有成功经验，善于总结',
      '有快消尤其餐饮和特渠成功经验者优先，有app地推经验优先',
      '抗压能力强， 有耐心，热爱水果和生鲜行业，有一定的规划商品能力的优先考虑',
      '热爱销售工作，性格乐观开朗，有强烈的责任心和进取心',
      '具有较强的人际沟通能力和亲和力'
  ],
	status: 1,
	order: 1,
  isTop: 0,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
  id: 4,
	key: 'society', 
	title: '视频剪辑',
	desc: '负责公司产品的视频后期处理，对视频制作数量负责',
	category: 'function',
  place: 'hangzhou',
	department: '广告部',
	date: '2022年01月01日',
  experience: '不限',
  education: '大专及以上',
  href: 'https://www.zhipin.com',
  contact: 'xxx@hr.com',
  duty: [             
      '负责公司产品的视频后期处理，对视频制作数量负责',
      '确保视频呈现的效果，对视频时长、完播率、播放量等指标负责',
      '能保质、保量、按时效完成视频需求'
  ],
  require: [
      '大专以及上学历，性别不限，美术设计、视觉传达等相关专业优先考虑',
      '精通PS、PR、AE等后期制作软件',
      '良好的团队合作能力、沟通表达能力'
  ],
  pluses: ['有过大型项目合作经验，尤其跨国合作，了解欧美风格'],
	status: 1,
	order: 1,
  isTop: 0,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
  id: 5,
	key: 'society', 
	title: 'SDR专员',
	desc: '',
	category: 'operating',
  place: 'beijing',
	department: '运营中心',
	date: '2022年04月01日',
  experience: '不限',
  education: '不限',
  href: 'https://www.zhipin.com',
  contact: 'xxx@hr.com',
  duty: [
      '通过电话寻找商机，并进行初步筛选，充分挖掘客户的详细信息，包括需求及痛点特征、决策和购买力等，寻找并确认产品的销售机会',
      '通过企业微信、邮件等在线工具孵化目标客户，并通过客户反馈的行为和频次判断下一步运营思路',
      '面向目标市场积极主动地寻找新的潜在客户和转化机会'
  ],
  require: [
      '有B2B企业工作经验，对互联网和SaaS领域有了解，尤其 SaaS 营销转化漏斗流程，有1年以上电话销售经验优先',
      '具备良好的沟通、协作和组织能力',
      '知识面广，思维活跃，有创新意识和挑战精神',
      '自我学习能力强，性格乐观开朗，有强烈的责任心和进取心'
  ],
	status: 1,
	order: 1,
  isTop: 0,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
  id: 6,
	key: 'society', 
	title: '数据开发工程师（上海）',
	desc: '基于HADOOP和MPP大数据平台，负责数据接入、数据清洗、数据加工',
	category: 'data',
  place: 'shanghai',
	department: '数据中心',
	date: '2022年01月01日',
  experience: '1~3年',
  education: '不限',
  href: 'https://www.zhipin.com',
  contact: 'xxx@hr.com',
  tag: ['quick'],
  duty: [
      '熟悉和理解运营商业务需求，基于HADOOP和MPP大数据平台，负责数据接入、数据清洗、数据加工等',
      '基于需求进行模型构建、程序设计及代码开发；为业务问题分析及营销推荐提供高效数据支撑',
      '能对数据进行分析与探索'
  ],
  require: [
      '统招全日制本科及以上学历，统计学、数学、计算机信息类、数据挖掘等相关专业，数据开发和分析1~3年工作经验',
      '熟练掌握数据库基础、了解数据库开发基本技术；1年及以上的PG、Hive、vertica、Mysql等数据库开发经验，至少熟悉一种主流数据库',
      '精通SQL/HQL，精通存储过程和函数，有良好的SQL编程习惯',
      '熟悉linux环境和命令；shell编程经验，了解python的优先',
      '具备良好的客户需求理解能力、良好的沟通和表达能力、责任心强、细致认真，热爱数据开发与分析工作'
  ],
  pluses: [
      '有电信运营商工作经验，特别是熟悉标签和画像数据者优先；有建模经验者优先',
      '熟悉M域业务和数据 待遇从优'
  ],
	status: 1,
	order: 1,
  isTop: 0,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
  id: 7,
	key: 'society', 
	title: '数据开发工程师（上海）',
	desc: '基于HADOOP和MPP大数据平台，负责数据接入、数据清洗、数据加工',
	category: 'data',
  place: 'hangzhou',
	department: '数据中心',
	date: '2022年01月01日',
  experience: '1~3年',
  education: '不限',
  href: 'https://www.zhipin.com',
  contact: 'xxx@hr.com',
  tag: ['quick'],
  duty: [
      '熟悉和理解运营商业务需求，基于HADOOP和MPP大数据平台，负责数据接入、数据清洗、数据加工等',
      '基于需求进行模型构建、程序设计及代码开发；为业务问题分析及营销推荐提供高效数据支撑',
      '能对数据进行分析与探索'
  ],
  require: [
      '统招全日制本科及以上学历，统计学、数学、计算机信息类、数据挖掘等相关专业，数据开发和分析1~3年工作经验',
      '熟练掌握数据库基础、了解数据库开发基本技术；1年及以上的PG、Hive、vertica、Mysql等数据库开发经验，至少熟悉一种主流数据库',
      '精通SQL/HQL，精通存储过程和函数，有良好的SQL编程习惯',
      '熟悉linux环境和命令；shell编程经验，了解python的优先',
      '具备良好的客户需求理解能力、良好的沟通和表达能力、责任心强、细致认真，热爱数据开发与分析工作'
  ],
  pluses: [
      '有电信运营商工作经验，特别是熟悉标签和画像数据者优先；有建模经验者优先',
      '熟悉M域业务和数据 待遇从优'
  ],
	status: 1,
	order: 1,
  isTop: 0,
	createTime: new Date(),
	modifyTime: new Date(),
},
])