db.kcoco_page_hot_activity.insertMany([
{
	title: '极客培训——全企业运营（一）',
	desc: '策划学就是其中很重要的一种，对企业的经营与管理实行科学策划，是企业经营与管理现代化建设中很重要的一个环节。',
	status: 1,
	date: '2022-02-01 20:00:00',
	location: '线上直播',
	href: '/activity/detail',
	btnText: '点击查看',
	cover: '/images/activity/hot/d2.png',
	type: '',
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '云上视听——数据质量（一）',
	desc: '手把手叫你如何搭建数据库全量统计，实战训练第一讲：快速上手webpack，插件化和矢量化。',
	status: 1,
	date: '2022-03-02 19:00:00',
	location: '线上直播',
	href: '/activity/detail',
	btnText: '点击查看',
	cover: '/images/activity/hot/c2.png',
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '玩转前端——服务器搭建（一）',
	desc: '品牌营销，营销的就是品牌的形象，其目的就是要在顾客心中塑造出一个理想的品牌形象来，那么围绕品牌营销的目的，在具体的品牌营销活动中就需要去做大量的工作。',
	status: 1,
	date: '2022-03-12 15:00:00',
	location: '线上直播',
	href: '/activity/detail',
	btnText: '点击查看',
	cover: '/images/activity/hot/b2.png',
	type: '',
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '极客培训——企业运营（二）',
	desc: '各学科、各工种在不断地融合、发展，品牌营销活动与策划科学相结合，以策划科学来指导品牌营销活动，是社会生产发展的必然结果。',
	status: 1,
	date: '2022-03-18 16:00:00',
	location: '线上直播',
	href: '/activity/detail',
	btnText: '点击查看',
	cover: '/images/activity/hot/d1.png',
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '直播课程——全量统计（一）',
	desc: '网站排名监控、传播数据分析、网站访问数量统计分析、访问人群分析、咨询统计分析、网页浏览深度统计分析、热门关键字访问统计分析。',
	status: 1,
	date: '2022-04-08 15:00:00',
	location: '线上直播',
	href: '/activity/detail',
	btnText: '点击查看',
	cover: '/images/activity/hot/a3.png',
	type: 'vip',
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '云上视听——数据质量（二）',
	desc: '顺利地实现这个目标而进行的品牌营销策划，就是要以品牌形象的塑造和传播为研究的重点，在掌握了大量的信息资料的前提下，遵循系统性、可行性、针对性、创造性的原则。',
	status: 1,
	date: '2022-04-15 17:00:00',
	location: '线上直播',
	href: '/activity/detail',
	btnText: '点击查看',
	cover: '/images/activity/hot/c1.png',
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '玩转前端——服务器搭建（二）',
	desc: '如何有效避免数据漏洞，如何快速还原设置，今晚9点，大神带你飞。',
	status: 1,
	date: '2022-04-23 20:00:00',
	location: '线上直播',
	href: '/activity/detail',
	btnText: '点击查看',
	cover: '/images/activity/hot/b1.png',
	type: 'new',
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '直播课程——全量统计（二）',
	desc: '个性化配置菜单，无需写大量代码，全部拖拉抓一把抓极客实现。',
	status: 1,
	date: '2022-05-08 20:00:00',
	location: '线上直播',
	href: '/activity/detail',
	btnText: '点击查看',
	cover: '/images/activity/hot/a2.png',
	type: 'vip',
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
{
	title: '直播课程——全量统计（三）',
	desc: '手把手叫你如何搭建数据库全量统计，实战训练第一讲：快速上手webpack，插件化和矢量化，网站排名监控、传播数据分析、网站访问数量统计分析、访问人群分析、咨询统计分析、网页浏览深度统计分析、热门关键字访问统计分析。',
	status: 1,
	date: '2022-06-01 16:00:00',
	location: '线上直播',
	href: '/activity/detail',
	btnText: '点击查看',
	cover: '/images/activity/hot/a1.png',
	type: 'vip',
	order: 1,
	createTime: new Date(),
	modifyTime: new Date(),
},
])