db.kcoco_page_tdk.insertMany([
{
    name: '首页',
    path: '/index',
    title: 'yy科技——10000万家供应商的信赖选择',
    description:
      'yy科技是一家很强大的公司，服务过上万家客户，一直深耕于游戏、大数据、餐饮、教育等行业，被业界评委最佳服务良心企业。',
    keywords: '科技,水果,蔬菜,智能系统,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-香蕉',
    path: '/product/fruits/banana',
    title: '香蕉_yy科技_水果联盟',
    description:
      '香蕉中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '科技,水果,香蕉,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-水蜜桃',
    path: '/product/fruits/peach',
    title: '水蜜桃_yy科技_水果联盟_桃子',
    description:
      '水蜜桃是一种营养价值非常高的水果，含有糖分，蛋白质，膳食纤维，钙，磷，铁等多种矿物质和维生素。',
    keywords: '桃子,水果,水蜜桃,联盟,peach',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-石榴',
    path: '/product/fruits/pomegranate',
    title: '石榴_yy科技_水果联盟_桃子',
    description:
      '石榴是一种营养价值非常高的水果，含有糖分，蛋白质，膳食纤维，钙，磷，铁等多种矿物质和维生素。',
    keywords: '石榴,水果,石榴汁,联盟,pomegranate',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-猕猴桃',
    path: '/product/fruits/kiwi',
    title: '猕猴桃_yy科技_水果联盟',
    description:
      '猕猴桃中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '科技,水果,猕猴桃,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-牛油果',
    path: '/product/fruits/avocado',
    title: '牛油果_热量水果_yy科技_水果联盟',
    description:
      '牛油果中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '科技,水果,牛油果,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-芒果',
    path: '/product/fruits/mongo',
    title: '芒果_热带水果_yy科技_水果联盟',
    description:
      '芒果中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: 'yy科技,水果,芒果,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-山竹',
    path: '/product/fruits/mangosteen',
    title: '山竹_热带水果_yy科技_水果联盟',
    description:
      '山竹中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '山竹,水果,热带水果,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-葡萄',
    path: '/product/fruits/grape',
    title: '葡萄_热带水果_yy科技_水果联盟',
    description:
      '葡萄中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '葡萄,水果,紫色,绿色,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-柠檬',
    path: '/product/fruits/lemon',
    title: '柠檬_热带水果_yy科技_水果联盟',
    description:
      '柠檬中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '柠檬,水果,酸味,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-荔枝',
    path: '/product/fruits/litchi',
    title: '荔枝_清热水果_yy科技_水果联盟',
    description:
      '荔枝中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '荔枝,水果,汽水,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-火龙果',
    path: '/product/fruits/piyata',
    title: '火龙果_红色水果_yy科技_水果联盟',
    description:
      '火龙果中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '火龙果,水果,红色水果,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-羊角蜜',
    path: '/product/fruits/croissant',
    title: '羊角蜜_青瓜_yy科技_水果联盟',
    description:
      '羊角蜜中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '羊角蜜,水果,青瓜,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-哈密瓜',
    path: '/product/fruits/hami',
    title: '哈密瓜_青瓜_yy科技_水果联盟',
    description:
      '哈密瓜中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '哈密瓜,水果,青瓜,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-无花果',
    path: '/product/fruits/fig',
    title: '无花果_季节水果_yy科技_水果联盟',
    description:
      '无花果中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '无花果,水果,红色,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-青枣',
    path: '/product/fruits/jujube',
    title: '青枣_水分_yy科技_水果联盟',
    description:
      '青枣中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '青枣,水果,绿色水果,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-苹果',
    path: '/product/fruits/apple',
    title: '苹果_常见水果_yy科技_水果联盟',
    description:
      '苹果中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '苹果,水果,绿色水果,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-柚子',
    path: '/product/fruits/shaddock',
    title: '柚子_常见水果_yy科技_水果联盟',
    description:
      '柚子中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '柚子,水果,绿色水果,联盟,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-枇杷',
    path: '/product/fruits/loquat',
    title: '枇杷_枇杷膏_yy科技_水果联盟',
    description:
      '枇杷中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '枇杷,水果,清热解毒,健康,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-李子',
    path: '/product/fruits/plum',
    title: '李子_枇杷膏_yy科技_水果联盟',
    description:
      '李子中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '李子,水果,清热解毒,健康,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-橘子',
    path: '/product/fruits/orange',
    title: '橘子_果汁_yy科技_水果联盟',
    description:
      '橘子中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '橘子,水果,维C,健康,橙汁',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-樱桃',
    path: '/product/fruits/cherry',
    title: '樱桃_车厘子_yy科技_水果联盟',
    description:
      '樱桃中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '樱桃,水果,cherry,健康,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-柿子',
    path: '/product/fruits/persimmon',
    title: '柿子_去火_yy科技_水果联盟',
    description:
      '柿子中所含的矿物质镁、钾和其他元素较多，尽管这些矿物质对身体有益，但食用过多会导致体内微量元素无法保持平衡。',
    keywords: '柿子,水果,柿子饼,健康,美食',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-红萝卜',
    path: '/product/vegetables/radish',
    title: '红萝卜_红色_yy科技_蔬菜_绿色',
    description:
      '红萝卜是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '红萝卜,素菜,绿色蔬菜,健康,炒菜',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-大葱',
    path: '/product/vegetables/onion',
    title: '大葱_调味_yy科技_蔬菜_绿色',
    description:
      '大葱是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '大葱,素菜,绿色蔬菜,健康,配菜',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-黄瓜',
    path: '/product/vegetables/cucumber',
    title: '黄瓜_干拌_yy科技_蔬菜_绿色',
    description:
      '黄瓜是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '黄瓜,减肥,绿色蔬菜,健康,配菜',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-菜苔',
    path: '/product/vegetables/bolt',
    title: '菜苔_yy科技_蔬菜_绿色',
    description:
      '菜苔是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '菜苔,素菜,绿色蔬菜,健康,炒菜',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-苋菜',
    path: '/product/vegetables/amaranthus',
    title: '苋菜_含锌_yy科技_蔬菜_绿色',
    description:
      '苋菜是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '苋菜,心血管预防,绿色蔬菜,健康,炒菜',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-藕',
    path: '/product/vegetables/lotus',
    title: '藕_根部_yy科技_蔬菜_绿色',
    description:
      '藕是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '藕,农作物,绿色蔬菜,健康,莲花',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-香菇',
    path: '/product/vegetables/mushroom',
    title: '香菇_蘑菇_yy科技_蔬菜_绿色',
    description:
      '香菇是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '香菇,配菜,绿色蔬菜,健康',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-白菜',
    path: '/product/vegetables/cabbage',
    title: '白菜_扣肉_yy科技_蔬菜_绿色',
    description:
      '白菜是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '白菜,配菜,绿色蔬菜,健康,白菜粉条',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-豌豆',
    path: '/product/vegetables/peas',
    title: '豌豆_yy科技_蔬菜_绿色',
    description:
      '豌豆是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '豌豆,僵尸,绿色蔬菜,健康,豌豆射手',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-苦瓜',
    path: '/product/vegetables/bilter',
    title: '苦瓜_夏天清热_yy科技_蔬菜_绿色',
    description:
      '苦瓜是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '苦瓜,清热解毒,绿色蔬菜,健康',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-芹菜',
    path: '/product/vegetables/celery',
    title: '芹菜_营养很高_yy科技_蔬菜_绿色',
    description:
      '芹菜是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '芹菜,清热解毒,绿色蔬菜,健康,营养价值',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-生姜',
    path: '/product/vegetables/ginger',
    title: '生姜_去腥_yy科技_蔬菜_绿色',
    description:
      '生姜是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '生姜,清热解毒,绿色蔬菜,健康,生炒',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-茄子',
    path: '/product/vegetables/eggplant',
    title: '茄子_紫色_yy科技_蔬菜',
    description:
      '茄子是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: 'eggplant,烧烤,绿色蔬菜,健康,番茄科',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-辣椒',
    path: '/product/vegetables/echili',
    title: '辣椒_红色_yy科技_驱寒必备',
    description:
      '辣椒是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '辣椒,四川湖南,绿色蔬菜,健康,去风湿',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-南瓜',
    path: '/product/vegetables/pumpkin',
    title: '南瓜_万圣节_yy科技_甜味蔬菜',
    description:
      '南瓜是一种营养价值非常高的食物，里面含有非常丰富的维生素以及碳水化合物，还含有蛋白质。能够被身体很好的吸收以及利用，能够让代谢的速度变得更快，还可以让身体各个器官的发育变得更好，身体就能更加健康。',
    keywords: '南瓜,南瓜车,绿色蔬菜,健康,冬瓜',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-AI语音',
    path: '/product/ai/speech',
    title: 'AI语音_智能应用_yy科技',
    description:
      '智能语音技术的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: '智能语音,科技,应用,AI',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-AI识别',
    path: '/product/ai/discriminate',
    title: 'AI识别_智能应用_yy科技',
    description:
      'AI识别技术的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: '智能识别,科技,应用,AI,AI系统',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-AI算法',
    path: '/product/ai/algorithm',
    title: 'AI算法_科技创新_服务_智能应用_yy科技',
    description:
      'AI算法技术的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: '离线算法,科技,应用,AI,神经网络',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-企业云',
    path: '/product/ai/enterprise',
    title: '企业云_私有化部署_智能创新_yy科技',
    description:
      '企业云技术的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: '企业云,科技,应用,云数据,大数据',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-数字云',
    path: '/product/ai/digital',
    title: '数字云_数字化改革_智能创新_yy科技',
    description:
      '数字云技术的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: '数字云,科技,数字化,云数据,大数据',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-清水',
    path: '/product/ai/qingshui',
    title: '清水_智能研判系统_智能创新_yy科技',
    description:
      '清水技术的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: '清水,科技创新,数字化,AI,大数据',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-数影',
    path: '/product/ai/shuying',
    title: '数影_计算引擎_智能创新_yy科技',
    description:
      '数影是一款大数据产品，的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: '数影,数字机算,密码学,AI,大数据',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-天眼杀',
    path: '/product/ai/tianyan',
    title: '天眼杀_实时追踪_智能创新_yy科技',
    description:
      '天眼杀是一款大数据产品，的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: '天眼杀,网络追踪,覆盖场景,AI,大数据',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-蹄蹄',
    path: '/product/ai/titi',
    title: '蹄蹄智能办公_敏捷BI_智能创新_yy科技',
    description:
      '蹄蹄智能办公是一款大数据产品，的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: '蹄蹄智能办公,BI,覆盖场景,数据解析,报表',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-colgi',
    path: '/product/ai/colgi',
    title: 'colgi_干预系统_智能创新_yy科技_智能推荐',
    description:
      'colgi是一款大数据产品，的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: 'colgi,大数据模拟,覆盖场景,AI,大数据',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-细雨',
    path: '/product/ai/xiyu',
    title: '细雨_AI大数据_智能创新_yy科技_智能推荐',
    description:
      '细雨是一款大数据产品，的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: '细雨,大数据模拟,数据敏感,AI,大数据',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-无人机',
    path: '/product/ai/uav',
    title: 'uav_智能无人机_智能创新_yy科技_智能作业',
    description:
      'uav是一款大数据产品，的研究是以语音识别技术为开端，可以追溯到20世纪50年代。随着信息技术的发展，智能语音技术已经成为人们信息获取和沟通最便捷、最有效的手段。',
    keywords: '智能无人机,人工替代,犯罪追踪,AI,智能作业',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-聚类算法',
    path: '/product/dataserver/neuralcluster',
    title: '聚类算法_智能算法_智能应用_yy科技',
    description:
      '聚类算法主要是指人脑的神经网络，它是人工神经网络的技术原型。人脑是人类思维的物质基础，思维的功能定位在大脑皮层，后者含有大约10^11个神经元，每个神经元又通过神经突触与大约103个其它神经元相连，形成一个高度复杂高度灵活的动态网络。',
    keywords: '算法,聚类算法,遗产算法,AI,MATLAB',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-离线算法',
    path: '/product/dataserver/offlinealgorithm',
    title: '离线算法_实时算法_智能应用_yy科技',
    description:
      '离线算法主要是指人脑的神经网络，它是人工神经网络的技术原型。人脑是人类思维的物质基础，思维的功能定位在大脑皮层，后者含有大约10^11个神经元，每个神经元又通过神经突触与大约103个其它神经元相连，形成一个高度复杂高度灵活的动态网络。',
    keywords: '离线算法,聚类算法,遗产算法,AI,JOA',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-实时开发',
    path: '/product/dataserver/onlinedevelop',
    title: '实时开发_实时算法_智能应用_yy科技',
    description:
      '实时开发主要是指人脑的神经网络，它是人工神经网络的技术原型。人脑是人类思维的物质基础，思维的功能定位在大脑皮层，后者含有大约10^11个神经元，每个神经元又通过神经突触与大约103个其它神经元相连，形成一个高度复杂高度灵活的动态网络。',
    keywords: '实时开发,数据开发,遗产算法,AI,大数据',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-离线开发',
    path: '/product/dataserver/offlinedevelop',
    title: '离线开发_离线计算_智能应用_yy科技',
    description:
      '离线开发主要是指人脑的神经网络，它是人工神经网络的技术原型。人脑是人类思维的物质基础，思维的功能定位在大脑皮层，后者含有大约10^11个神经元，每个神经元又通过神经突触与大约103个其它神经元相连，形成一个高度复杂高度灵活的动态网络。',
    keywords: '离线开发,数据开发,数据资产,AI,大数据',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-推荐系统',
    path: '/product/dataserver/recommend',
    title: '智能推荐系统_大数据推荐_智能应用_yy科技',
    description:
      '智能推荐系统主要是指人脑的神经网络，它是人工神经网络的技术原型。人脑是人类思维的物质基础，思维的功能定位在大脑皮层，后者含有大约10^11个神经元，每个神经元又通过神经突触与大约103个其它神经元相连，形成一个高度复杂高度灵活的动态网络。',
    keywords: '智能推荐系统,数据开发,数据资产,协同过滤,人工智能',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '产品-神经网络',
    path: '/product/dataserver/neuralnetwork',
    title: '神经网络_智能算法_智能应用_yy科技',
    description:
      '生物神经网络主要是指人脑的神经网络，它是人工神经网络的技术原型。人脑是人类思维的物质基础，思维的功能定位在大脑皮层，后者含有大约10^11个神经元，每个神经元又通过神经突触与大约103个其它神经元相连，形成一个高度复杂高度灵活的动态网络。',
    keywords: '算法,神经网络,遗产算法,AI',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '解决方案-教育',
    path: '/solution/education',
    title: '教育行业解决方案_智能算法_yy科技',
    description:
      '教育行业解决方案大数据技术的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换而言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”。',
    keywords: '教育行业,solution,数字化,数字转型',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '解决方案-大数据',
    path: '/solution/bigdata',
    title: '大数据行业解决方案_智能算法_yy科技',
    description:
      '大数据技术的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换而言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”。',
    keywords: '大数据,bigdata,数字化,数字转型',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '解决方案-金融',
    path: '/solution/finance',
    title: '金融行业解决方案_智能算法_yy科技',
    description:
      '金融行业解决方案的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换而言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”。',
    keywords: '金融行业解决方案,solution,数据上云,数字转型',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '解决方案-餐饮',
    path: '/solution/food',
    title: '餐饮行业解决方案_智能算法_yy科技',
    description:
      '餐饮行业解决方案的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换而言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”。',
    keywords: '餐饮行业解决方案,智能选址,solution,数据上云,数字转型',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '解决方案-游戏',
    path: '/solution/game',
    title: '游戏行业解决方案_智能算法_yy科技',
    description:
      '游戏行业解决方案的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换而言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”。',
    keywords: '游戏行业解决方案,智能AI,机器学习,数字转型',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '解决方案-传统制造',
    path: '/solution/manufacture',
    title: '传统制造行业解决方案_智能算法_yy科技',
    description:
      '传统制造行业解决方案的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换而言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”。',
    keywords: '传统制造行业解决方案,机器制造,机器学习,人力成本',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '解决方案-电商',
    path: '/solution/online',
    title: '电商行业解决方案_智能算法_yy科技',
    description:
      '电商行业解决方案的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换而言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”。',
    keywords: '电商行业解决方案,数据接入,智能系统,投资',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '解决方案-私有化',
    path: '/solution/personal',
    title: '私有化行业解决方案_私有化部署_智能算法_yy科技',
    description:
      '私有化行业解决方案的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换而言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”。',
    keywords: '私有化行业解决方案,智能系统,投资',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '解决方案-交通',
    path: '/solution/traffic',
    title: '交通行业解决方案_智能监控_智能算法_yy科技',
    description:
      '交通行业解决方案的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换而言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”。',
    keywords: '交通行业解决方案,智能系统,智能智慧,AI监控',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '客户案例主页',
    path: '/case',
    title: '客户案例_品牌活动_超值划算_yy科技',
    description:
      '客户案例，上千家客户信赖选择，它的特色在于对海量数据进行分布式数据挖掘。但它必须依托云计算的分布式处理、分布式数据库和云存储、虚拟化技术。',
    keywords: '案例,行业聚焦,数字化,数字转型',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '客户案例详情',
    path: '/case/detail',
    title: '案例详情_客户案例_超值划算_yy科技',
    description:
      '客户案例详情，解决方案，上千家客户信赖选择，它的特色在于对海量数据进行分布式数据挖掘。但它必须依托云计算的分布式处理、分布式数据库和云存储、虚拟化技术。',
    keywords: '案例详情,行业聚焦,数字化,数字转型',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '活动主页',
    path: '/activity',
    title: '热门活动_品牌活动_超值划算_yy科技',
    description:
      '热门活动，品牌活动，直播活动，它的特色在于对海量数据进行分布式数据挖掘。但它必须依托云计算的分布式处理、分布式数据库和云存储、虚拟化技术。',
    keywords: '活动,科技,数字化,数字转型',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '活动详情',
    path: '/activity/detail',
    title: '活动详情_热门活动_品牌活动_超值划算_yy科技',
    description:
      '热门活动，品牌活动，直播活动，它的特色在于对海量数据进行分布式数据挖掘。但它必须依托云计算的分布式处理、分布式数据库和云存储、虚拟化技术。',
    keywords: '活动详情,科技,数字化,数字转型',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '联系我们',
    path: '/service/contact',
    title: '联系我们_商务合作_合作伙伴_yy科技',
    description:
      '联系我们，公司地址，杭州市科技达到特色在于对海量数据进行分布式数据挖掘。但它必须依托云计算的分布式处理、分布式数据库和云存储、虚拟化技术。',
    keywords: '联系我们,公司地址,合作关系,投资合作',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '帮助中心',
    path: '/service/help',
    title: '帮助中心_企业资料_白皮书_yy科技',
    description:
      '帮助中心，文档查询，搜索你需要的资料，杭州市科技达到特色在于对海量数据进行分布式数据挖掘。但它必须依托云计算的分布式处理、分布式数据库和云存储、虚拟化技术。',
    keywords: '帮助中心,help,资源,白皮书',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '资源中心',
    path: '/service/resource',
    title: '资源中心_资源下载_白皮书_yy科技',
    description:
      '资源中心，资源下载，搜索你需要的资料，杭州市科技达到特色在于对海量数据进行分布式数据挖掘。但它必须依托云计算的分布式处理、分布式数据库和云存储、虚拟化技术。',
    keywords: '资源中心,下载,分享,白皮书',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '隐私声明',
    path: '/service/declare',
    title: '隐私政策_yy科技',
    description:
      'yy科技隐私政策，搜索你需要的资料，杭州市科技达到特色在于对海量数据进行分布式数据挖掘。但它必须依托云计算的分布式处理、分布式数据库和云存储、虚拟化技术。',
    keywords: '隐私政策',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '新闻主页',
    path: '/about/news',
    title: '文章列表_文热门章_行业资讯_yy科技',
    description:
      '行业资讯，是中国IDC行业最权威的资讯年刊，主要针对IDC行业及互联网、金融、云计算等领域发行，全书约400页，分为全彩印刷本和电子版两个版本，预计印刷版发行量在2.5万册，电子版发行总量超25万本。',
    keywords: '新闻,资讯,最新,数字转型,数字化',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '新闻详情',
    path: '/about/news/detail',
    title: '',
    description: '',
    keywords: '',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '公司介绍',
    path: '/about/company',
    title: '公司详情_yy科技_联系我们',
    description:
      'yy科技——10000万家供应商的信赖选择，yy科技是一家很强大的公司，权威的资讯年刊，主要针对IDC行业及互联网、金融、云计算等领域发行，全书约400页，分为全彩印刷本和电子版两个版本，预计印刷版发行量在2.5万册，电子版发行总量超25万本。',
    keywords: '科技,yy,最新,加入yy科技,数字化',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '加入我们',
    path: '/about/joinus',
    title: '加入我们_招兵买马_yy科技_联系我们',
    description:
      'yy科技——10000万家供应商的信赖选择，yy科技是一家很强大的公司，权威的资讯年刊，主要针对IDC行业及互联网、金融、云计算等领域发行，全书约400页，分为全彩印刷本和电子版两个版本，预计印刷版发行量在2.5万册，电子版发行总量超25万本。',
    keywords: '简历投递,加入我们,最新,加入yy科技,数字化',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '内容标签体系',
    path: '/about/tag',
    title: '热门标签_资源整合_yy科技',
    description:
      '热门标签，知识图谱分享，yy科技——10000万家供应商的信赖选择，yy科技是一家很强大的公司，权威的资讯年刊，主要针对IDC行业及互联网、金融、云计算等领域发行，全书约400页，分为全彩印刷本和电子版两个版本，预计印刷版发行量在2.5万册，电子版发行总量超25万本。',
    keywords: '热门标签,加入我们,最新,知识图谱,数字化',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  {
    name: '表单',
    path: '/form',
    title: '表单填写_信息收集_合作_yy科技',
    description:
      'yy科技——10000万家供应商的信赖选择，yy科技是一家很强大的公司，权威的资讯年刊，主要针对IDC行业及互联网、金融、云计算等领域发行，全书约400页，分为全彩印刷本和电子版两个版本，预计印刷版发行量在2.5万册，电子版发行总量超25万本。',
    keywords: '表单,合作模式,yy科技,智能系统,数字化',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
  //default 设置 当key匹配不到时，返回默认tdk配置
  {
    name: 'default',
    title: 'yy科技——10000万家供应商的信赖选择',
    description: 'yy科技是一家很强大的公司。',
    keywords: '科技,水果,蔬菜,智能系统,供应商',
    status: 1,
    createTime: new Date(),
    modifyTime: new Date(),
  },
])